import React from "react";
import {
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiTailwindcss,
  SiNodedotjs,
  SiPython,
  SiMongodb,
  SiDocker,
  SiGooglecloud,
  SiPostgresql,
  SiLaravel,
  SiAwsamplify,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiMinio,
  SiMocha,
  SiPhp,
  SiBootstrap,
  SiExpress,
  SiGit,
  SiPostman,
  SiCloudflare,
} from "react-icons/si";
import {
  LuBrain,
  LuRefreshCw,
} from "react-icons/lu";

export const skillIcons: Record<string, React.ReactNode> = {
  "Next.js": <SiNextdotjs />,
  "React": <SiReact />,
  "Typescript": <SiTypescript />,
  "Javascript": <SiJavascript />,
  "Tailwind CSS": <SiTailwindcss />,
  "Laravel": <SiLaravel />,
  "Node.js": <SiNodedotjs />,
  "Python": <SiPython />,
  "MongoDB": <SiMongodb />,
  "Docker": <SiDocker />,
  "Google Cloud Platform (GCP)": <SiGooglecloud />,
  "PostgreSQL": <SiPostgresql />,
  "Amazon Web Service (AWS)": <SiAwsamplify />,
  "HTML": <SiHtml5 />,
  "CSS": <SiCss3 />,
  "Figma": <SiFigma />,
  "MinIO": <SiMinio />,
  "Mocha": <SiMocha />,
  "PHP": <SiPhp />,
  "Bootstrap": <SiBootstrap />,
  "Express.js": <SiExpress />,
  "Git": <SiGit />,
  "Postman": <SiPostman />,
  "Cloud Computing": <SiCloudflare />,
  "NoSQL": <SiMongodb />,
  "SQL/PostgreSQL": <SiPostgresql />,
  "Critical Thinking": <LuBrain />,
  "Adaptability": <LuRefreshCw />,
  "hapi.js": <span className="text-xs font-bold">hapi</span>,
  "Restify": <span className="text-xs font-bold">restify</span>,
  "i18n": <span className="text-xs font-bold">i18n</span>,
};
