import React from "react";
import {
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiTailwindcss,
  SiNodedotjs,
  SiPython,
  SiMongodb,
  SiDocker,
  SiGooglecloud,
  SiPostgresql,
  SiLaravel,
  SiAwsamplify,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiMinio,
  SiMocha,
  SiPhp,
  SiBootstrap,
  SiExpress,
  SiGit,
  SiPostman,
  SiMysql,
  SiRedux,
  SiVite,
  SiKotlin,
  SiLeaflet,
} from "react-icons/si";
import { GiArtificialIntelligence } from "react-icons/gi";
import { TbCloudComputing, TbSql } from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";

export const skillIcons: Record<string, React.ReactNode> = {
  "Next.js": <SiNextdotjs />,
  "React": <SiReact />,
  "Typescript": <SiTypescript />,
  "Javascript": <SiJavascript />,
  "Tailwind CSS": <SiTailwindcss />,
  "Laravel": <SiLaravel />,
  "Node.js": <SiNodedotjs />,
  "Python": <SiPython />,
  "MongoDB": <SiMongodb />,
  "Docker": <SiDocker />,
  "Google Cloud Platform (GCP)": <SiGooglecloud />,
  "PostgreSQL": <SiPostgresql />,
  "Amazon Web Service (AWS)": <SiAwsamplify />,
  "HTML": <SiHtml5 />,
  "CSS": <SiCss3 />,
  "Figma": <SiFigma />,
  "MinIO": <SiMinio />,
  "Mocha": <SiMocha />,
  "PHP": <SiPhp />,
  "Bootstrap": <SiBootstrap />,
  "Express.js": <SiExpress />,
  "Git": <SiGit />,
  "Postman": <SiPostman />,
  "NoSQL": <SiMongodb />,
  "SQL/PostgreSQL": <SiPostgresql />,
  "MySQL": <SiMysql />,
  "Artificial Intelligence (AI)": <GiArtificialIntelligence />,
  "Cloud Computing": <TbCloudComputing />,
  "SQL": <TbSql />,
  "Redux": <SiRedux />,
  "Vite": <SiVite />,
  "Kotlin": <SiKotlin />,
  "Leaflet.js": <SiLeaflet />,
  "Visual Studio Code": <VscVscode />,
};
